version: '3.8'

services:
  bot:
    build: .
    container_name: dxa-number-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./sessions:/app/sessions
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
